import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/component/NavBar/Navbar'
import SolidPage from '@/component/SolidPage/SolidPage'
import Stickman from '@/elments/SittingStickMan/Stickman'
import Chair from '@/elments/SittingStickMan/Chair'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar />
        <SolidPage>
          {children}

        </SolidPage>
      </body>
    </html>
  )
}
